# Bun configuration for shadcn-universe

[install]
# Use exact versions to avoid breaking changes
exact = true

# Freeze the lockfile after install
frozen = false

# Cache settings
cache = "~/.bun/install/cache"

[install.scopes]
# Optional: Add custom registry scopes here if needed

[dev]
# Development server settings (optional)
# These are handled by Next.js but can be configured here

